version: '3.1'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/hosts:/etc/nginx/conf.d
      - ./www:/var/www
      - ./logs:/var/log/nginx
    links:
      - php
  php:
    image: php
    user: '1000:1000'
    links:
      - mysql
    volumes:
      - ./www:/var/www
      - $HOME/.gitconfig:/home/php/.gitconfig
      - ./.symfony:/home/php/.symfony
    secrets:
      - id_rsa
  vue:
    image: vue
    links:
      - php
    user: '1000:1000'
    volumes:
      - ./vue/project1:/home/js/www
      - $HOME/.gitconfig:/home/js/.gitconfig
    secrets:
      - id_rsa
  mysql:
    image: percona:8
    restart: always
    ports:
        - "3306:3306"
    volumes:
        - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret

secrets:
  id_rsa:
    file: ~/.ssh/id_rsa
